/**
 * Generates src/components/ui/icon-data.ts from the local Phosphor set in
 * public/static/icons. Only the curated chrome glyphs are inlined, so the
 * bundle carries ~40 paths rather than 9,072 files, and every icon renders
 * as real SVG with currentColor (no <img>, no mask, no network).
 *
 *   npx tsx scripts/build-icons.ts
 */
import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";

const ICONS_DIR = path.resolve(__dirname, "../public/static/icons");
const OUT = path.resolve(__dirname, "../src/components/ui/icon-data.ts");

/** name in the chrome → phosphor file name (regular weight). */
const CHROME_ICONS: Record<string, string> = {
  // navigation & chrome
  back: "arrow-left",
  forward: "arrow-right",
  close: "x",
  settings: "gear",
  logout: "sign-out",
  search: "magnifying-glass",
  chevronDown: "caret-down",
  chevronRight: "caret-right",
  chevronUp: "caret-up",
  chevronLeft: "caret-left",
  more: "dots-three",
  check: "check",
  plus: "plus",
  minus: "minus",
  // documents
  deck: "monitor-play",
  doc: "file-text",
  folder: "folder",
  duplicate: "copy",
  trash: "trash",
  download: "download-simple",
  upload: "upload-simple",
  file: "file-arrow-up",
  // editing
  text: "text-t",
  layout: "layout",
  image: "image",
  chart: "chart-bar",
  notes: "note",
  undo: "arrow-counter-clockwise",
  redo: "arrow-clockwise",
  regenerate: "arrows-clockwise",
  moveUp: "arrow-up",
  moveDown: "arrow-down",
  drag: "dots-six-vertical",
  // status & meta
  sparkle: "sparkle",
  quality: "seal-check",
  warning: "warning",
  error: "warning-circle",
  info: "info",
  success: "check-circle",
  brand: "tag",
  palette: "palette",
  globe: "globe",
  present: "play",
  sun: "sun",
  moon: "moon",
  command: "command",
  keyboard: "keyboard",
  eye: "eye",
  grid: "squares-four",
  panelLeft: "sidebar-simple",
  panelRight: "sidebar",
  stop: "x-circle",
  revert: "arrow-u-up-left",
  list: "list-numbers",

  // template gallery — one per blueprint in src/lib/templates/library.ts
  tplBlank: "file-dashed",
  tplPitch: "rocket-launch",
  tplSales: "handshake",
  tplBoard: "presentation-chart",
  tplResearch: "flask",
  tplLaunch: "sparkle",
  tplTraining: "graduation-cap",
  tplMarketing: "megaphone",
  tplStrategy: "compass",
  tplInvestor: "trend-up",
  tplKeynote: "microphone",
  tplCourse: "student",
  tplStudio: "square-half",
  tplMemo: "diamond",
  tplSpotlight: "star",
  tplVisual: "images-square",
  tplProposal: "clipboard-text",
  tplReport: "books",
  tplWhitepaper: "book-open",
  tplCase: "trophy",
  tplOnePager: "lightning",
};

/** Pull the inner markup out of a Phosphor SVG, dropping the spacer rect. */
function extractBody(file: string): string {
  const raw = readFileSync(file, "utf8");
  const inner = raw.replace(/^[\s\S]*?<svg[^>]*>/, "").replace(/<\/svg>\s*$/, "");
  return inner
    .replace(/<rect\s+width="256"\s+height="256"\s+fill="none"\s*\/>/g, "")
    .replace(/\s+/g, " ")
    .trim();
}

function main() {
  const entries: string[] = [];
  const missing: string[] = [];

  for (const [key, phosphor] of Object.entries(CHROME_ICONS)) {
    const file = path.join(ICONS_DIR, "regular", `${phosphor}.svg`);
    try {
      const body = extractBody(file);
      entries.push(`  ${key}: ${JSON.stringify(body)},`);
    } catch {
      missing.push(`${key} (${phosphor}.svg)`);
    }
  }

  if (missing.length > 0) {
    console.error("Missing Phosphor glyphs:\n  " + missing.join("\n  "));
    process.exit(1);
  }

  const out = `/**
 * GENERATED by scripts/build-icons.ts — do not edit.
 * Inlined Phosphor (MIT) glyph bodies; see THIRD_PARTY_LICENSES.md.
 */

export const ICON_PATHS = {
${entries.join("\n")}
} as const;

export type IconName = keyof typeof ICON_PATHS;
`;
  writeFileSync(OUT, out);
  console.log(`wrote ${OUT} with ${entries.length} icons`);
}

main();
