/**
 * One-time font self-hosting: downloads woff2 files (latin subset, weights
 * 400/600/700) for every font family used by the built-in themes, writes
 * them to public/fonts/, and generates src/styles/fonts.css with @font-face
 * rules. After this runs once, typography is fully offline.
 *
 *   npx tsx scripts/fetch-fonts.ts
 */
import { mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import { themes } from "../src/lib/themes/data";

const WEIGHTS = [400, 500, 600, 700, 800];
const FONTS_DIR = path.resolve(__dirname, "../public/fonts");
const CSS_OUT = path.resolve(__dirname, "../src/styles/fonts.css");
// A modern-Chrome UA makes Google Fonts serve woff2.
const UA =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0 Safari/537.36";

function familiesFromThemes(): string[] {
  const set = new Set<string>();
  for (const theme of Object.values(themes)) {
    set.add(theme.fonts.heading);
    set.add(theme.fonts.body);
    if (theme.fonts.numeric) set.add(theme.fonts.numeric);
  }
  return [...set].sort();
}

function slug(family: string): string {
  return family.toLowerCase().replace(/\s+/g, "-");
}

async function fetchCss(family: string): Promise<string | null> {
  const url = new URL("https://fonts.googleapis.com/css2");
  url.searchParams.set(
    "family",
    `${family}:wght@${WEIGHTS.join(";")}`,
  );
  url.searchParams.set("display", "swap");
  const res = await fetch(url, {
    headers: { "User-Agent": UA },
    signal: AbortSignal.timeout(20_000),
  });
  if (!res.ok) return null;
  return res.text();
}

interface Face {
  family: string;
  weight: string;
  unicodeRange: string | null;
  url: string;
}

function parseFaces(css: string, family: string): Face[] {
  const faces: Face[] = [];
  const blocks = css.match(/@font-face\s*{[^}]+}/g) ?? [];
  for (const block of blocks) {
    // latin subset only (marked by comment before block in GF css; filter by
    // unicode-range containing U+0000-00FF)
    const range = block.match(/unicode-range:\s*([^;]+);/)?.[1] ?? null;
    if (range && !range.includes("U+0000-00FF")) continue;
    const weight = block.match(/font-weight:\s*(\d+)/)?.[1] ?? "400";
    const url = block.match(/src:\s*url\((https:[^)]+\.woff2)\)/)?.[1];
    if (!url) continue;
    faces.push({ family, weight, unicodeRange: range, url });
  }
  return faces;
}

async function main() {
  const families = familiesFromThemes();
  console.log(`families: ${families.length}`);
  mkdirSync(FONTS_DIR, { recursive: true });

  const cssRules: string[] = [
    "/* Generated by scripts/fetch-fonts.ts — self-hosted theme fonts. */",
  ];
  const failed: string[] = [];

  for (const family of families) {
    const css = await fetchCss(family);
    if (!css) {
      failed.push(family);
      continue;
    }
    const faces = parseFaces(css, family);
    if (faces.length === 0) {
      failed.push(family);
      continue;
    }
    for (const face of faces) {
      const filename = `${slug(family)}-${face.weight}.woff2`;
      const res = await fetch(face.url, {
        headers: { "User-Agent": UA },
        signal: AbortSignal.timeout(30_000),
      });
      if (!res.ok) continue;
      writeFileSync(
        path.join(FONTS_DIR, filename),
        Buffer.from(await res.arrayBuffer()),
      );
      cssRules.push(
        `@font-face {
  font-family: "${family}";
  font-style: normal;
  font-weight: ${face.weight};
  font-display: swap;
  src: url("/fonts/${filename}") format("woff2");
}`,
      );
    }
    process.stdout.write(`\rfetched ${family}                    `);
  }
  console.log();
  writeFileSync(CSS_OUT, cssRules.join("\n\n") + "\n");
  console.log(
    `wrote ${CSS_OUT} with ${cssRules.length - 1} @font-face rules`,
  );
  if (failed.length) console.warn("FAILED families:", failed.join(", "));
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
